#    _________                                  __ __________        __   
#   /   _____/__ ________ ______   ____________/  |\______   \ _____/  |_ 
#   \_____  \|  |  \____ \\____ \ /  _ \_  __ \   __\    |  _//  _ \   __\
#   /        \  |  /  |_> >  |_> >  <_> )  | \/|  | |    |   (  <_> )  |  
#  /_______  /____/|   __/|   __/ \____/|__|   |__| |______  /\____/|__|  
#          \/      |__|   |__|                             \/             
#
#                   SupportBot v5.2
#                   Created by ¬© 2020 Emerald Services
#                   License: MIT

#Bot Indentification
Token: "BOT_TOKEN_HERE"
Prefix: "!"
Bot_Name: "SupportBot"

BotActivity: "SupportBot v5.2"
ActivityType: "PLAYING"

EmbedColour: "#4bbf5c"
EmbedFooter: "SupportBot | The #1 Supportive Discord Bot"

# Colour Settings
ErrorColour: "#ff3030"
SuccessColour: "#4bbf5c"
WarningColour: "#fca117" 

# Role Settings
AutoRole: "Member"
StaffRole: "Support"

locked_role: "@everyone"
everyone: "@everyone"

Department_Role_1: "Support"
Department_Role_2: "Sales"
Department_Role_3: "Support"

# Ticket Department Settings
Ticket_Department_1: "Support"
Ticket_Department_2: "Sales"
Ticket_Department_3: "Other"

Ticket_Department_Emoji_1: "üü¢"
Ticket_Department_Emoji_2: "üîµ"
Ticket_Department_Emoji_3: "üî¥"

# Ticket Settings
category: "Tickets"
Ticket_Colour: "#4bbf5c"
Ticket_Channel_Name: "ticket"
Ticket_Logs: "ticket-logs"

Transcript_Log: "ticket-data"
Transcript_Title: "Support Transcript"

Ticket_Closing: "‚ö† Your ticket is now closing!"  
Ticket_Closure: "Looks like you have come to the end of your support ticket\nPlease confirm that you want to close your ticket."
Closure_Confirm_Word: "confirm"

Ticket_Message: "Your support ticket has been opened successfully\nPlease allow us some time to reach out to you."
Default_Ticket_Reason: "No Subject"

# Welcome & Leave
WelcomeChannel: "welcome"
WelcomeMessage: "Welcome to the server!"

LeaveChannel: "welcome"
LeaveMessage: "Thank you for visiting us!"

# Announcement Settings
Announcement_Title: "SupportBot Announcement"
Announcement_Channel: "announcements"
Announcement_Tag_Role: "@everyone"

# Poll Settings
Poll_Channel: "polls"
Poll_Title: "üìä Polls"

Reaction_Poll_1: "‚úÖ"
Reaction_Poll_2: "‚ùé"

# Suggestion Settings
Suggestion_Title: "SupportBot Suggestions"
Suggestion_Channel: "suggestions"

suggestyes: "‚úÖ"
suggestno: "‚ùé"

# Report Settings
Report_Channel: "reports"
Report_Title: "SupportBot Report"

# Link Settings
LINKS_TITLE: "SupportBot Links"

LINKS: 
  "Discord": "https://discord.gg/"
  "Twitter": "https://twitter.com/"
  "Website": "https://example.com/"
  "AddMore": "AddMoreIfYouWant"

# Bot Command Settings
Add_Command: "add"
Remove_Command: "remove"
Ticket_Command: "ticket"
Close_Command: "close"
Forceclose_Command: "forceclose"
Rename_Command: "rename"
Lockchat_Command: "lock"
UnLockchat_Command: "unlock"
Announcement_Command: "announce"
Say_Command: "say"
Suggest_Command: "suggest"
Ping_Command: "ping"
Help_Command: "help"
Link_Command: "links"
Poll_Command: "poll"
Report_Command: "report"
Setup_Command: "setup"
