#      ___                            _    ___        _
#    / __> _ _  ___  ___  ___  _ _ _| |_ | . > ___ _| |_
#     \__ \| | || . \| . \/ . \| '_> | |  | . \/ . \ | |
#     <___/`___||  _/|  _/\___/|_|   |_|  |___/\___/ |_|
#                |_|  |_|
#
#           SupportBot created by Emerald Services
#           Installed with MIT License
#
#           Discord Support: https://dsc.gg/emerald-dev
#           Official Documentation: https://emeraldsrv.com/wiki
#           Third-Party Documentation: https://emeraldsrv.com/third-party
#
#           Messages Configuration

Info:
  Title: "About Us"
  Description: "SupportBot is an open-sourced support system for discord. It's completely free to use with high amounts of customization to match your own brand."
  Button: "Visit Site"
  URL: "https://emeraldsrv.com"
  Colour: "#f74343"

Welcome:
  Embed:
    Colour: "#f74343"
    Title: "Welcome to ServerName"
    Message: "> :smile: %joined_user% has just landed!"
    Thumbnail: "BOT"

    ImageEnabled: false
    ImageURL: "https://animagelink.png/"

Leave:
  Embed:
    Colour: "#f74343"
    Title: "Goodbye!"
    Message: "> :slight_frown: %joined_user% has recently dropped out!"
    Thumbnail: "BOT"

    ImageEnabled: false
    ImageURL: "https://animagelink.png/"

Suggestions:
  Sent_Title: "Suggestion Sent!"
  Sent: "> :white_check_mark: **You have successfully sent a suggestion.**"
  NoSelfVote: "> :x: **You cannot vote on your own suggestion.**"
  RemoveVoteButton: "Remove Vote"

Ticket:

#  Available Placeholders:

#  %ticketusername% - User who created the ticket.
#  <@%ticketauthor%> - Tags the user who created the ticket.
#  <#%ticketid%> - Mentions the ticket channel.

  TicketAuthorTitle: "%ticketusername%'s Ticket"
  TicketTitle: "Support Ticket"
  TicketMessage: "> Hello <@%ticketauthor%>, Thank you for creating a support ticket\nPlease wait patiently whilst a member of our team reaches out to you."
  TicketThumbnail: "https://images.emojiterra.com/google/android-pie/512px/1f39f.png"
  TicketCreatedAlert: "> :ticket: Ticked Created: <#%ticketid%>"
  TicketExists: "> âŒ Ticket already exists"
  TicketClaim: "> :white_check_mark: Ticket claimed by" #The user who claimed the ticket will be added to the end of this message
  TicketUnclaim: "> :white_check_mark: Ticket unclaimed by" #The user who claimed the ticket will be added to the end of this message

  DisableInvites: "> ðŸ”’ Invites have been disabled for this ticket." 
  EnableInvites: "> ðŸ”“ Invites have been enabled for this ticket." 

#  Available Placeholders:

#  <@%user%> - Tags the user who was added to the ticket.

  AddUserToTicket_Title: "âž• Add User!"
  AddUserToTicket: "> To add a user to this ticket, Tag them."

  RemovedUserFromTicket_Title: "âž– Removed User!"
  RemovedUserFromTicket: "> <@%user%> has been `Removed` from this ticket"

  Blacklisted: "> :x: You are not allowed to open a ticket"
  Muted: "> :x: You are `Muted` and therefore not allowed to open any tickets"
  InvalidSubject: "> No Reason Provided!"

  TranscriptSavedMessage: "ðŸ“ **Transcript Saved!**"
  TicketLockMessage: "âŒ **Ticket Locked!**"
  TicketDeleteMessage: "âš  **Ticket Deleting!**" 

  ClosingTicket: "> :warning: You have requested to close your support ticket."
  ConfirmClose: "> Please confirm closing the ticket by clicking the button below."
  CloseTimeout: "> Ticket close confirmation timed out."

  ClaimTickets:
    ClaimTitle: "Incoming Support Request!"
    ClaimMessage: "> A new ticket has been created by <@!%user%>. Click the button below to claim this ticket."
    ClaimMessage_Edit: "> <#%channel%> was claimed by <@!%user%>."

    ClaimedTitle: "Ticket Claimed!"
    Claimed: "> You have successfully claimed this ticket. <#%channel%>"
    NoPermsToClaimTitle: "Error, no permissions!"
    NoPermsToClaim: "> :x: **Err!** You do not permissions to claim this ticket."

    ReassigningTitle: "Reassigning!..."
    ReassigningMessage: "> <@%user%> did not claim the ticket. **Reassigning...**"

TicketStats: 
  OpenTickets: "âœ… Open Tickets"
  TotalTickets: "ðŸŽ« Total Tickets"
  ResponseTime: "â±ï¸ Average Response Time"

  Title: "Your Ticket Stats"

Error:
  IncorrectPerms: "> :x: **Err!** You do not have the correct permissions to use this."
  InvalidChannel: "> :x: **Err!** Channel not found. Please create it!"
  UserNotFound: "> :x: **Err!** This user doesn't exist, Are they in this server?"
  NoValidTicket: "> :warning: You cannot execute this command here."
  TicketExists: "> :warning: This ticket cannot be opened, It already exists!"




  
