#        _________                                  __ __________        __   
#       /   _____/__ ________ ______   ____________/  |\______   \ _____/  |_ 
#       \_____  \|  |  \____ \\____ \ /  _ \_  __ \   __\    |  _//  _ \   __\
#       /        \  |  /  |_> >  |_> >  <_> )  | \/|  | |    |   (  <_> )  |  
#      /_______  /____/|   __/|   __/ \____/|__|   |__| |______  /\____/|__|  
#              \/      |__|   |__|                             \/             
#
#                      SupportBot version 6.2
#                      Created by Emerald Services
#                      Installed with MIT License
#
#                      Support Server: discord.gg/jspKFcE

# General Bot Configuration

Token: "BOT_TOKEN_HERE"
Prefix: "-"
Bot_Name: "SupportBot"

BotActivity: "-help | SupportBot"
StreamingURL: "https://www.twitch.tv/YOUR_TWITCH_NAME"
# Debe establecer ActivityType en STREAMING para que la direcci√≥n URL de streaming funcione en el estado de los bots.

ActivityType: "PLAYING"
# El estado de la actividad puede ser 

DeleteMessages: "true"

# Embed Configuration

EmbedColour: "#04b545"
EmbedFooter: "SupportBot El #1 bot de discordia de apoyo"

ErrorColour: "#d12519"
SuccessColour: "#04b545"
WarningColour: "#fca117" 

# Role Configuration

AutoRole: "true"
# Estableciendo "AutoRole para 'true' el bot aplicar√° autom√°ticamente el rol siguiente cuando los miembros se unan. Establecer en 'false' para desactivar esta funci√≥n.
AutoRole_Role: "Miembro"
LockdownRole: "@everyone"

Staff: "Personal"
Admin: "Admin"

# Ticket Configuration

TicketChannel: "ticket"
TicketCategory: "Tickets"
TicketLog: "ticket-logs"
TranscriptLog: "transcripts"
TicketSubject: "description"
# TicketSubject: "description" significa que el sujeto (motivo) del billete se mostrar√° en la descripci√≥n del canal si se establece en "embed" se mostrar√° dentro de la incrustaci√≥n.

AllowTicketMentions: "true"
# Establecer en "true" para permitir que el boleto mencione al autor y al equipo de apoyo.
# Establecer en "false" para desautorizar las menciones dentro de los boletos.

# Ticket Panel (Ticket Reaction Create)

ReactionTickets: "true"
ReactionMessage: "React with %reaction_emoji% para crear un Ticket de Soporte!"
ReactionChannel: "crear-ticket"
ReactionPanel_Description: "true"
ReactionDescription: "Cree un ticket de soporte para contactar a un miembro del personal."
ReactionEmoji: "üì©"
# Custom Emojis: <:test:EMOJI_ID>
ReactionPanel_Thumbnail: true
ReactionThumbnail: "https://hotemoji.com/images/dl/5/ticket-emoji-by-twitter.png"
ReactionPanel_Image: true
ReactionImage: "https://wallpapercave.com/wp/wp4462546.jpg"

Ticket_Thumbnail: "https://images.emojiterra.com/google/android-pie/512px/1f39f.png"
Ticket_Title: "Server Support | %ticketusername%"
TicketMessage: "Hola <@%ticketauthor%>, Gracias por crear un ticket de apoyo\nPor favor, espere pacientemente mientras un miembro de nuestro equipo se acerca a usted."
NoTicketSubject: "No Reason Provided!"
TicketCreatedAlert: ":ticket: Se ha creado su ticket de soporte: <#%ticketid%>"
TranscriptTitle: "Transcripci√≥n de entradas"

AddedUser: "üëç <@%user%> se ha a√±adido a este billete"
RemovedUser: "üëç <@%user%> ha sido retirado de este boleto"

ClosingTicket: ":warning: Ha solicitado cerrar su ticket de soporte."
ClosingConfirmation_Word: "confirm"
CloseConfirmation: "true"
# CloseConfirmation a true har√° que los usuarios confirmen que quieren cerrar un billete, la configuraci√≥n a false simplemente cerrar√° el ticket.

# Ticket Department Configuration

TicketDepartments: "true"
# Esta opci√≥n habilite o deshabilite los departamentos de tickets. Compensar "false" Los departamentos de entradas no funcionar√°n.

AllowStaff: "true"
# AllowStaff es una opci√≥n para si desea o no que los usuarios con el rol "Personal" puedan ver dentro de los tickets. Si se establece falso "Personal" no ver√° los boletos.

DepartmentEmoji_1: "üôã"
DepartmentEmoji_2: "üí∏"
DepartmentEmoji_3: "üìó"
# Ticket emojis, los emojis son lo que los usuarios tendr√°n que reaccionar con orden para proceder furthur si los departamentos est√°n habilitados.

DepartmentTitle_1: "Apoyo"
DepartmentTitle_2: "Facturaci√≥n"
DepartmentTitle_3: "Otro"
# Ticket department title, Este es el t√≠tulo de un departamento de tickets para ayudar a los usuarios a saber lo que est√° disponible.

DepartmentRole_1: "Apoyo"
DepartmentRole_2: "Admin"
DepartmentRole_3: "Apoyo"
# Los roles de tickets son los roles que podr√°n acceder a los boletos dependiendo del departamento que se haya elegido.

# System Message Configuration

SystemMessages: "true"

SystemMessage_Channel: "smensajes-del-sistema"
SystemMessage_Type: "embed"
# Hay 2 tipos de c√≥mo puede enviar mensajes del sistema, 'normal' or 'embed'
SystemMessage_Icon: "USER"

Welcome_Title: "Usuario unido!"
WelcomeMessage: "Hola %member%, Bienvenido a %guildname%!"
# %member% definir el usuario que se uni√≥ y %guildnamne% define el nombre del servidor.

Leave_Title: "¬°Usuario a la izquierda!"
LeaveMessage: "Adios %member%, Gracias por visting %guildname%!"
# %member% definir el usuario que se uni√≥ y %guildnamne% define el nombre del servidor.

SystemMessage_EmbedFooter: "false"

# LINKS Configuration

LinksTitle: "Enlaces r√°pidos"

LINKS:
  "Website": "https://www.example.com"
  "Store": "https://store.example.com"
  "Discord": "https://discord.gg/example"
# "Twitter": "https://twitter.com/example"

# Suggestions Configuration

SuggestionChannel: "Sugerencias"
SuggestionTitle: "Sugerencia"
SuggestionStarter: "¬øQu√© te gustar√≠a sugerir?"
SuggestReact_1: üëç
SuggestReact_2: üëé

# Announcement Configuration

AnnouncementChannel: "anuncios"
AnnouncementTitle: "Anuncio de nombre de servidor"
AnnouncementIcon: "https://i.imgur.com/HbkZyB7.png"

AnnouncementStarter: "¬øQu√© te gustar√≠a anunciar?"

# Moderation System Configuration

BanTitle: "User Banned!"
DaysBannedFor: 7
BanLogColour: "#D911B4"

KickTitle: "User Kicked!"
KickLogColour: "#D9B111"

ModThumbnail: "https://i.imgur.com/l6P3DF6.png"
ModLogChannel: "mod-logs"

PruneLogTitle: "Bulk Delete"
PruneThumbnail: "https://i.imgur.com/OAgW2vR.png"
PruneColour: "#1BA30C"

# General Command Configuration

HelpCommand: "ayuda"
LinksCommand: "enlaces"
PingCommand: "senal"
SuggestCommand: "cugerir"

# Support Command Configuration

NewTicket: "boleto"
CloseTicket: "cerca"
AddUser: "anadir"
RemoveUser: "eliminar"
RenameTicket: "renombrar"

# Staff Command Configuration

BotSay: "decir"
PurgeMessage: "purge"

# Admin Command Configuration

AnnounceCommand: "anunciar"
BanUser: "ban"
KickUser: "kick"

# Commmand Descriptions

NewTicketDesc: "Crear un nuevo ticket de soporte"
AnnounceDesc: "Crear un anuncio de servidor"
CloseTicketDesc: "Cierre su ticket de soporte"
LinksDesc: "Ver algunos enlaces importantes"
PingDesc: "Obtener la latencia del bot"
HelpDesc: "Obtener una lista de todos los comandoss"
RemoveUserDesc: "Eliminar un usuario de un ticket de soporte"
AddUserDesc: "Add un usuario a un ticket de soporte"
SuggestionDesc: "Crear una sugerencia de servidor"
BotSayDesc: "Di algo con el bot"
BanDesc: "Prohibir a un/una miembro de este servidor."
KickDesc: "Patea a un/una miembro de este servidor."
PurgeDesc: "Purga los mensajes del chat."

# Error / Warining Messages

IncorrectPerms: ":x: **Err!** No tiene los permisos correctos para utilizar este comando."
InvalidChannel: ":x: **Err!** Canal no encontrado. ¬°Por favor, cr√©alo!"
UserNotFound: ":x: **Err!** Este usuario no existe, ¬øest√°n en este servidor?"
NoValidTicket: ":warning: No puede ejecutar este comando aqu√≠. Este comando se utiliza al cerrar un vale."
TicketExists: ":warning: Este billete no se puede abrir, ¬°Ya existe!"
