#        _________                                  __ __________        __   
#       /   _____/__ ________ ______   ____________/  |\______   \ _____/  |_ 
#       \_____  \|  |  \____ \\____ \ /  _ \_  __ \   __\    |  _//  _ \   __\
#       /        \  |  /  |_> >  |_> >  <_> )  | \/|  | |    |   (  <_> )  |  
#      /_______  /____/|   __/|   __/ \____/|__|   |__| |______  /\____/|__|  
#              \/      |__|   |__|                             \/             
#
#                      SupportBot version 6.1
#                      Created by Emerald Services
#                      Installed with MIT License
#
#                      Support Server: discord.gg/jspKFcE

# General Bot Configuration

Token: "BOT_TOKEN_HERE"
Prefix: "-"
Bot_Name: "SupportBot"

BotActivity: "-help | SupportBot"
StreamingURL: "https://www.twitch.tv/YOUR_TWITCH_NAME"
# Doit d√©finir ActivityType a STREAMING afin que l‚ÄôURL de streaming fonctionne dans le statut bots.

ActivityType: "PLAYING"
# L‚Äô√©tat d‚Äôactivit√© peut √™tre PLAYING, WATCHING, LISTENING ou STREAMING.

DeleteMessages: "true"

# Embed Configuration

EmbedColour: "#04b545"
EmbedFooter: "SupportBot | The #1 Supportive Discord Bot"

ErrorColour: "#d12519"
SuccessColour: "#04b545"
WarningColour: "#fca117" 

# Role Configuration

AutoRole: "true"
# En parametre "AutoRole a 'true' le bot appliquera automatiquement le r√¥le ci-dessous lorsque les membres se joindra. Mis √† 'false' d√©sactiver cette fonctionnalite.
AutoRole_Role: "Membre"
LockdownRole: "@everyone"

Staff: "Personnel"
Admin: "Admin"

# Ticket Configuration

TicketChannel: "ticket"
TicketCategory: "Tickets"
TicketLog: "ticket-logs"
TranscriptLog: "transcripts"
TicketSubject: "description"
# TicketSubject: "description" signifie que le sujet (reason) du billet sera affich√© sur la description du canal s‚Äôil est d√©fini pour "embed" il sera affich√© dans l‚Äôint√©gration.

AllowTicketMentions: "true"
# Mis a "true" pour permettre au billet de mentionner l‚Äôauteur et l‚Äô√©quipe de soutien.
# Mis a "false" pour d√©sa autoriser les mentions dans les billets.


# Ticket Panel (Ticket Reaction Create)

ReactionTickets: "true"
ReactionMessage: "R√©agissez avec %reaction_emoji% pour cr√©er un ticket de support !"
ReactionChannel: "creer-billet"
ReactionPanel_Description: "true"
ReactionDescription: "Cr√©ez un ticket de support pour contacter un membre du personnel."
ReactionEmoji: "üì©"
# Custom Emojis: <:test:EMOJI_ID>
ReactionPanel_Thumbnail: true
ReactionThumbnail: "https://hotemoji.com/images/dl/5/ticket-emoji-by-twitter.png"
ReactionPanel_Image: true
ReactionImage: "https://wallpapercave.com/wp/wp4462546.jpg"

Ticket_Thumbnail: "https://images.emojiterra.com/google/android-pie/512px/1f39f.png"
Ticket_Title: "Prise en charge du serveur | %ticketusername%"
TicketMessage: "Bonjour <@%ticketauthor%>, Merci d‚Äôavoir cr√©√© un billet de support\nS‚Äôil vous pla√Æt attendre patiemment pendant qu‚Äôun membre de notre √©quipe vous tend la main."
NoTicketSubject: "Aucune raison fournie!"
TicketCreatedAlert: ":ticket: Votre ticket de support a √©t√© cr√©√© : <#%ticketid%>"
TranscriptTitle: "Transcription du billet"

AddedUser: "üëç <@%user%> a ete ajoute a ce billet"
RemovedUser: "üëç <@%user%> a ete retir√© de ce billet"

ClosingTicket: ":warning: Vous avez demand√© de fermer votre billet de soutien."
ClosingConfirmation_Word: "confirm"
CloseConfirmation: "true"
# CloseConfirmation a vrai fera confirmer aux utilisateurs qu‚Äôils veulent fermer un leur billet, les param√®tres √† faux va juste fermer le billet.

# Ticket Department Configuration

TicketDepartments: "true"
# Cette option permet ou d√©sactive les d√©partements de billetterie. Si d√©finissez faux d√©partements de billets ne fonctionnera pas

AllowStaff: "true"
# AllowStaff est une option pour savoir si oui ou non vous voulez les utilisateurs avec le "Staff" r√¥le pour √™tre en mesure de voir √† l‚Äôint√©rieur des billets. S‚Äôil est mis faux "Staff" ne affichera pas les billets.

DepartmentEmoji_1: "üôã"
DepartmentEmoji_2: "üí∏"
DepartmentEmoji_3: "üìó"
# Emojis billet, les emojis sont ce que les utilisateurs devront r√©agir avec inorder pour proc√©der furthur si les d√©partements sont activ√©s.

DepartmentTitle_1: "Soutien"
DepartmentTitle_2: "Facturation"
DepartmentTitle_3: "Autres"
# Titre du d√©partement des billets, C‚Äôest le titre d‚Äôun service de billetterie pour aider les utilisateurs √† savoir ce qui est disponible.

DepartmentRole_1: "Soutien"
DepartmentRole_2: "Admin"
DepartmentRole_3: "Soutien"
# Les r√¥les de billets sont les r√¥les qui seront en mesure d‚Äôacc√©der aux billets en fonction du minist√®re qui a √©t√© choisi.

# System Message Configuration

SystemMessages: "true"

SystemMessage_Channel: "messages-systeme"
SystemMessage_Type: "embed"
# Il existe 2 types de la fa√ßon dont vous pouvez envoyer des messages syst√®me, 'normal' or 'embed'
SystemMessage_Icon: "USER"

Welcome_Title: "Utilisateur rejoint!"
WelcomeMessage: "Bonjour %member%, Bienvenue √† %guildname%!"
# %member% d√©finir l‚Äôutilisateur qui a rejoint et %guildnamne% d√©finit le nom du serveur.

Leave_Title: "Utilisateur √† gauche!"
LeaveMessage: "Au revoir %member%, Merci d‚Äôavoir visting %guildname%!"
# %member% d√©finir l‚Äôutilisateur qui est parti et %guildnamne% d√©finit le nom du serveur.

SystemMessage_EmbedFooter: "false"

# LINKS Configuration

LinksTitle: "Liens rapides"

LINKS:
  "Website": "https://www.example.com"
  "Store": "https://store.example.com"
  "Discord": "https://discord.gg/example"
# "Twitter": "https://twitter.com/example"

# Suggestions Configuration

SuggestionChannel: "suggestions"
SuggestionTitle: "Suggestion"
SuggestionStarter: "Qu‚Äôaimeriez-vous sugg√©rer?"
SuggestReact_1: üëç
SuggestReact_2: üëé

# Announcement Configuration

AnnouncementChannel: "annonces"
AnnouncementTitle: "Annonce servername"
AnnouncementIcon: "https://i.imgur.com/HbkZyB7.png"

AnnouncementStarter: "Qu‚Äôaimeriez-vous annoncer?"

# Moderation System Configuration

BanTitle: "User Banned!"
DaysBannedFor: 7
BanLogColour: "#D911B4"

KickTitle: "User Kicked!"
KickLogColour: "#D9B111"

ModThumbnail: "https://i.imgur.com/l6P3DF6.png"
ModLogChannel: "mod-logs"

PruneLogTitle: "Bulk Delete"
PruneThumbnail: "https://i.imgur.com/OAgW2vR.png"
PruneColour: "#1BA30C"


# General Command Configuration

HelpCommand: "aide"
LinksCommand: "liens"
PingCommand: "ping"
SuggestCommand: "suggerer"

# Support Command Configuration

NewTicket: "billet"
CloseTicket: "proche"
AddUser: "ajouter"
RemoveUser: "retirer"
RenameTicket: "renommer"

# Staff Command Configuration

BotSay: "dire"
PurgeMessage: "purge"

# Admin Command Configuration

AnnounceCommand: "annoncer"
BanUser: "ban"
KickUser: "kick"

# Commmand Descriptions

NewTicketDesc: "Cr√©er un nouveau ticket de support"
AnnounceDesc: "Cr√©er une annonce de serveur"
CloseTicketDesc: "Fermez votre billet de support"
LinksDesc: "View some important links"
PingDesc: "Obtenez la latence du bot"
HelpDesc: "Obtenez une liste de toutes les commandes"
RemoveUserDesc: "Supprimer un utilisateur d‚Äôun ticket de support"
AddUserDesc: "Ajouter un utilisateur √† un ticket de support"
SuggestionDesc: "Cr√©er une suggestion de serveur"
BotSayDesc: "Dites quelque chose avec le bot"
BanDesc: "Bannir un membre de ce serveur."
KickDesc: "Kick un membre de ce serveur."
PurgeDesc: "Purgez les messages du chat."

# Error / Warining Messages

IncorrectPerms: ":x: **Err!** Vous n‚Äôavez pas les autorisations correctes pour utiliser cette commande."
InvalidChannel: ":x: **Err!** Canal ina pas trouv√©. S‚Äôil vous pla√Æt le cr√©er!"
UserNotFound: ":x: **Err!** Vous ne pouvez pas ex√©cuter cette commande ici. Cette commande est utilis√©e lors de la fermeture d‚Äôun billet. ..."
NoValidTicket: ":warning: Vous ne pouvez pas ex√©cuter cette commande ici. Cette commande est utilis√©e lors de la fermeture d‚Äôun billet."
TicketExists: ":warning: Ce billet ne peut pas √™tre ouvert, il existe d√©j√†!"
